name: Container

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_container_and_push:
    runs-on: X64
    if: github.repository_owner == 'deepmodeling'
    strategy:
      matrix:
        dockerfile: ["gnu","intel","cuda"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/deepmodeling/abacus-${{ matrix.dockerfile }}
            registry.dp.tech/deepmodeling/abacus-${{ matrix.dockerfile }}
          tags: |
            type=semver,pattern={{version}},enable=${{ github.ref_type == 'tag' }}
            type=raw,value=latest

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Registry
        uses: docker/login-action@v3
        with:
          registry: registry.dp.tech
          username: ${{ secrets.DP_HARBOR_USERNAME }}
          password: ${{ secrets.DP_HARBOR_PASSWORD }}

      - name: Build and Push Container
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile.${{ matrix.dockerfile }}
          push: true
          cache-from: type=registry,ref=ghcr.io/deepmodeling/abacus-${{ matrix.dockerfile }}:latest
          cache-to: type=inline
